name: Create google cloud aiplatform lambda layer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          mkdir python
          pip install google-cloud-aiplatform -t python
          # Remove unnecessary files
          find python -type d -name "tests" -exec rm -rf {} +
          find python -type d -name "__pycache__" -exec rm -rf {} +
          find python -type d -name "*.dist-info" -exec rm -rf {} +
          find python -type d -name "*.egg-info" -exec rm -rf {} +
          # Zip the layer
          zip -r google-cloud-aiplatform.zip python

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: google-cloud-aiplatform
          path: google-cloud-aiplatform.zip
