name: Create google cloud aiplatform lambda layer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          mkdir python
          cd python
          pip3 install google-cloud-aiplatform -t .
          cd ..
          zip -r google-cloud-aiplatform.zip python

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: google-cloud-aiplatform
          path: google-cloud-aiplatform.zip
